// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyt1DSPNap5eCDzOawuEmyu7E2Sa-7Z90',
    appId: '1:89883313630:web:025cec10952ecba43f494f',
    messagingSenderId: '89883313630',
    projectId: 'isft182-39810',
    authDomain: 'isft182-39810.firebaseapp.com',
    storageBucket: 'isft182-39810.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDde-1AbanTezH5lJ52TSGGdG5SWKkTa3Y',
    appId: '1:89883313630:android:4a779edeb63378923f494f',
    messagingSenderId: '89883313630',
    projectId: 'isft182-39810',
    storageBucket: 'isft182-39810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGM9jmVnKyioB4OqAkBANkeb8FV2yJac4',
    appId: '1:89883313630:ios:46c2e454d9e010ca3f494f',
    messagingSenderId: '89883313630',
    projectId: 'isft182-39810',
    storageBucket: 'isft182-39810.firebasestorage.app',
    androidClientId: '89883313630-kg0rqprbk7fi5jh6rvi001g24m744gtd.apps.googleusercontent.com',
    iosClientId: '89883313630-njmrmg231fvtnop7n63seun6pidh2fqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGM9jmVnKyioB4OqAkBANkeb8FV2yJac4',
    appId: '1:89883313630:ios:46c2e454d9e010ca3f494f',
    messagingSenderId: '89883313630',
    projectId: 'isft182-39810',
    storageBucket: 'isft182-39810.firebasestorage.app',
    androidClientId: '89883313630-kg0rqprbk7fi5jh6rvi001g24m744gtd.apps.googleusercontent.com',
    iosClientId: '89883313630-njmrmg231fvtnop7n63seun6pidh2fqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyt1DSPNap5eCDzOawuEmyu7E2Sa-7Z90',
    appId: '1:89883313630:web:798f13762217c47b3f494f',
    messagingSenderId: '89883313630',
    projectId: 'isft182-39810',
    authDomain: 'isft182-39810.firebaseapp.com',
    storageBucket: 'isft182-39810.firebasestorage.app',
  );
}
